version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: inventario-db
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB
    ports:
      - "$DB_PORT:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
